openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /api/statistics/:
    get:
      tags:
      - api
      - statistics
      summary: Get All Sessions
      operationId: get_all_sessions_api_statistics__get
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          minimum: 1
          default: 1
          title: Page
      - name: pageSize
        in: query
        required: false
        schema:
          type: integer
          minimum: -1
          default: 10
          title: Pagesize
      - name: begin_timestamp
        in: query
        required: false
        schema:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Begin Timestamp
      - name: end_timestamp
        in: query
        required: false
        schema:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: End Timestamp
      - name: student_id
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Student Id
      - name: student_name
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Student Name
      - name: student_email
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Student Email
      - name: course_title
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Course Title
      - name: action_type
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Action Type
      - name: event_type
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Event Type
      - name: element_type
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Element Type
      - name: element_name
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Element Name
      responses:
        '200':
          description: Get statistics
          content:
            application/json:
              schema:
                type: array
                items: {}
                title: Response Get All Sessions Api Statistics  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      tags:
      - api
      - statistics
      summary: Create Session
      operationId: create_session_api_statistics__post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSessionData'
      responses:
        '201':
          description: Add new session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionData'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/statistics/{session_id}:
    get:
      tags:
      - api
      - statistics
      summary: Get Session By Id
      operationId: get_session_by_id_api_statistics__session_id__get
      parameters:
      - name: session_id
        in: path
        required: true
        schema:
          type: string
          title: Session Id
      responses:
        '200':
          description: Get session statistic
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionData'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - api
      - statistics
      summary: Delete Session
      operationId: delete_session_api_statistics__session_id__delete
      parameters:
      - name: session_id
        in: path
        required: true
        schema:
          type: string
          title: Session Id
      responses:
        '204':
          description: Delete a session statistic
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/statistics/page:
    post:
      tags:
      - api
      - statistics
      summary: Create Page
      operationId: create_page_api_statistics_page_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePageData'
        required: true
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
                title: Response Create Page Api Statistics Page Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/user/:
    get:
      tags:
      - api
      - user
      summary: Get All Users
      operationId: get_all_users_api_user__get
      responses:
        '200':
          description: List all users
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/User'
                type: array
                title: Response Get All Users Api User  Get
    post:
      tags:
      - api
      - user
      summary: Create User
      operationId: create_user_api_user__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'
        required: true
      responses:
        '201':
          description: Add new user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/user/{user_id}:
    get:
      tags:
      - api
      - user
      summary: Get User
      operationId: get_user_api_user__user_id__get
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
          title: User Id
      responses:
        '200':
          description: Retrieve a user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    put:
      tags:
      - api
      - user
      summary: Update User
      operationId: update_user_api_user__user_id__put
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
          title: User Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUser'
      responses:
        '200':
          description: Update user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - api
      - user
      summary: Delete User
      operationId: delete_user_api_user__user_id__delete
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
          title: User Id
      responses:
        '204':
          description: Delete a user
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/auth/sign-in:
    post:
      tags:
      - api
      - authorization
      summary: Signin
      operationId: signin_api_auth_sign_in_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInData'
        required: true
      responses:
        '200':
          description: User authorization
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/healthcheck/:
    get:
      tags:
      - api
      - healthcheck
      summary: Healthcheck
      operationId: healthcheck_api_healthcheck__get
      responses:
        '200':
          description: Healthcheck ping
          content:
            application/json:
              schema: {}
  /api/download/statistics:
    get:
      tags:
      - api
      - download
      summary: Download Data
      operationId: download_data_api_download_statistics_get
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          minimum: 1
          default: 1
          title: Page
      - name: pageSize
        in: query
        required: false
        schema:
          type: integer
          minimum: -1
          default: 10
          title: Pagesize
      - name: begin_timestamp
        in: query
        required: false
        schema:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Begin Timestamp
      - name: end_timestamp
        in: query
        required: false
        schema:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: End Timestamp
      - name: student_id
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Student Id
      - name: student_name
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Student Name
      - name: student_email
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Student Email
      - name: course_title
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Course Title
      - name: action_type
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Action Type
      - name: event_type
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Event Type
      - name: element_type
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Element Type
      - name: element_name
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Element Name
      responses:
        '200':
          description: Download statistics
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/download/sessions:
    get:
      tags:
      - api
      - download
      summary: Download Sessions
      operationId: download_sessions_api_download_sessions_get
      responses:
        '200':
          description: Download sessions
          content:
            application/json:
              schema: {}
components:
  schemas:
    CreatePageData:
      properties:
        page:
          type: string
          maxLength: 2083
          minLength: 1
          format: uri
          title: Page
        browser:
          type: string
          title: Browser
        title:
          type: string
          title: Title
        page_html:
          type: string
          title: Page Html
        window:
          $ref: '#/components/schemas/Window'
      type: object
      required:
      - page
      - browser
      - title
      - page_html
      - window
      title: CreatePageData
      example:
        browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit
        page: http://e.moevm.info
        page_html: <html></html>
        title: kakoy-to title
        window:
          height: 800
          width: 1200
    CreateSessionData:
      properties:
        student_id:
          type: integer
          title: Student Id
        session_id:
          type: string
          title: Session Id
        student:
          type: string
          title: Student
        email:
          type: string
          format: email
          title: Email
        course:
          type: string
          title: Course
        tabID:
          type: string
          title: Tabid
        url:
          type: string
          title: Url
        actions:
          items:
            $ref: '#/components/schemas/Payload'
          type: array
          title: Actions
      type: object
      required:
      - student_id
      - session_id
      - student
      - email
      - course
      - tabID
      - url
      title: CreateSessionData
      examples:
      - actions:
        - action_type: conversation
          element_html: <input/>
          element_name: сохранить
          element_type: button
          event_type: mousedown
          timestamp: '2026-10-07T07:50:52.023866'
        course: Курс молодого бойца
        email: iiivanov@edu.ru
        session_id: 1f2297b3-affb-420b-beb2-ea5ae488b4a0
        student: Иванов Иван
        student_id: 1
        url: https://e.moevm.info/course/view.php?id=2
      - actions:
        - action_type: hidden
          element_html: <input/>
          element_name: сохранить
          element_type: page
          event_type: visibilitychange
          timestamp: '2026-10-07T07:50:52.023874'
        course: Курс молодого бойца
        email: iiivanov@edu.ru
        session_id: 74686f52-b103-46ab-ad3c-54c3f129f1ea
        student: Иванов Иван
        student_id: 1
        url: https://e.moevm.info/course/view.php?id=2
      - actions:
        - action_type: visible
          element_html: <input/>
          element_name: сохранить
          element_type: page
          event_type: visibilitychange
          timestamp: '2026-10-07T07:50:52.023878'
        course: Курс молодого бойца
        email: iiivanov@edu.ru
        session_id: 9a3d2d42-0218-4dc7-afd4-57761abb4fe6
        student: Иванов Иван
        student_id: 1
        url: https://e.moevm.info/course/view.php?id=2
    CreateUser:
      properties:
        name:
          type: string
          title: Name
        surname:
          type: string
          title: Surname
        lastname:
          type: string
          title: Lastname
        email:
          type: string
          format: email
          title: Email
        password:
          type: string
          title: Password
      type: object
      required:
      - name
      - surname
      - lastname
      - email
      - password
      title: CreateUser
      example:
        email: iiivanov@edu.ru
        lastname: Иванович
        name: Иван
        password: sdfsdfwgesdgcx
        surname: Иванов
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Payload:
      properties:
        timestamp:
          type: string
          format: date-time
          title: Timestamp
        element_type:
          type: string
          title: Element Type
        element_name:
          type: string
          title: Element Name
        action_type:
          type: string
          title: Action Type
        event_type:
          type: string
          title: Event Type
        element_html:
          type: string
          title: Element Html
          description: The HTML content of the element
      type: object
      required:
      - element_type
      - element_name
      - action_type
      - event_type
      - element_html
      title: Payload
      examples:
      - action_type: conversation
        element_html: <input/>
        element_name: отправить
        element_type: button
        event_type: mousedown
        timestamp: '2026-10-07T07:50:52.021167'
      - action_type: hidden
        element_html: <input/>
        element_name: сохранить
        element_type: page
        event_type: visibilitychange
        timestamp: '2026-10-07T07:50:52.021176'
      - action_type: visible
        element_html: <input/>
        element_name: сохранить
        element_type: page
        event_type: visibilitychange
        timestamp: '2026-10-07T07:50:52.021177'
    Role:
      type: string
      enum:
      - admin
      - regular
      title: Role
    SessionData:
      properties:
        _id:
          type: string
          title: ' Id'
        student_id:
          type: integer
          title: Student Id
        session_id:
          type: string
          title: Session Id
        student:
          type: string
          title: Student
        email:
          type: string
          format: email
          title: Email
        tabID:
          type: string
          title: Tabid
        course:
          type: string
          title: Course
        url:
          type: string
          title: Url
        actions:
          items:
            $ref: '#/components/schemas/Payload'
          type: array
          title: Actions
      type: object
      required:
      - student_id
      - session_id
      - student
      - email
      - tabID
      - course
      - url
      title: SessionData
      examples:
      - actions:
        - action_type: conversation
          element_html: <input/>
          element_name: сохранить
          element_type: button
          event_type: mousedown
          timestamp: '2026-10-07T07:50:52.022042'
        course: Курс молодого бойца
        email: iiivanov@edu.ru
        id: 6f39710c-abdf-439b-af46-2a26f8808384
        session_id: 71bb7e51-2412-44b2-8659-d598e41a9bec
        student: Иванов Иван
        student_id: 1
        url: https://e.moevm.info/course/view.php?id=2
      - actions:
        - action_type: hidden
          element_html: <input/>
          element_name: сохранить
          element_type: button
          event_type: visibilitychange
          timestamp: '2026-10-07T07:50:52.022051'
        course: Курс молодого бойца
        email: iiivanov@edu.ru
        id: 89c9b8bb-1604-4d9c-8c0d-a94b0214c495
        session_id: b8e1b968-afe8-4442-94f2-500ef64e6532
        student: Иванов Иван
        student_id: 1
        url: https://e.moevm.info/course/view.php?id=2
      - actions:
        - action_type: visible
          element_html: <input/>
          element_name: сохранить
          element_type: page
          event_type: visibilitychange
          timestamp: '2026-10-07T07:50:52.022057'
        course: Курс молодого бойца
        email: iiivanov@edu.ru
        id: ce3ad975-4d8d-4a55-8b32-642c80e43859
        session_id: 96219a09-c821-40ba-9ae5-152ab51ffe11
        student: Иванов Иван
        student_id: 1
        url: https://e.moevm.info/course/view.php?id=2
    SignInData:
      properties:
        email:
          type: string
          format: email
          title: Email
        password:
          type: string
          title: Password
      type: object
      required:
      - email
      - password
      title: SignInData
      example:
        email: iiivanov@edu.ru
        password: sdfsdfwgesdgcx
    UpdateUser:
      properties:
        name:
          anyOf:
          - type: string
          - type: 'null'
          title: Name
        surname:
          anyOf:
          - type: string
          - type: 'null'
          title: Surname
        lastname:
          anyOf:
          - type: string
          - type: 'null'
          title: Lastname
        email:
          anyOf:
          - type: string
            format: email
          - type: 'null'
          title: Email
        position:
          anyOf:
          - $ref: '#/components/schemas/Role'
          - type: 'null'
        password:
          anyOf:
          - type: string
          - type: 'null'
          title: Password
      type: object
      required:
      - name
      - surname
      - lastname
      - email
      - position
      - password
      title: UpdateUser
      example:
        email: iiivanov@edu.ru
        lastname: Иванович
        name: Иван
        password: sdfsdfwgesdgcx
        position: regular
        surname: Иванов
    User:
      properties:
        _id:
          type: string
          title: ' Id'
        name:
          type: string
          title: Name
        surname:
          type: string
          title: Surname
        lastname:
          type: string
          title: Lastname
        email:
          type: string
          format: email
          title: Email
        position:
          $ref: '#/components/schemas/Role'
        password:
          type: string
          title: Password
      type: object
      required:
      - name
      - surname
      - lastname
      - email
      - position
      - password
      title: User
      example:
        email: iiivanov@edu.ru
        id: bf6e2523-6d0d-4e82-9206-c9ff6af373a1
        lastname: Иванович
        name: Иван
        password: sdfsdfwgesdgcx
        position: regular
        surname: Иванов
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    Window:
      properties:
        width:
          type: integer
          title: Width
        height:
          type: integer
          title: Height
      type: object
      required:
      - width
      - height
      title: Window
